site_name:        AnimatedOptimization.jl
repo_url:         https://github.com/schrimpf/AnimatedOptimization.jl
site_description: Optimization algorithms with animations.
site_author:      schrimpf

theme: journal

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - smarty
  - toc:
     permalink: True
  - sane_lists
  - admonition
  - footnotes
  - mdx_math
  

plugins:
  - bibtex:
     bib_file: "jmd/opt.bib"
     cite_style: "pandoc"

docs_dir: 'build'

nav:
  - Package Documentation: index.md
  - Notes on Algorithms: optimization.md